### ISSUE TITLE
Fail to resolve artifacts of types ejb, ejb-client, test-jar

### ISSUE THREAD

**Issue by kiroff** [commsen/bom-helper-maven-plugin#1]
Having dependencies like the following:
```
<dependency>
    <groupId>com.foo</groupId>
    <artifactId>bar-ejb</artifactId>
    <type>ejb</type>
    <version>0.0.1</version>
</dependency>
<dependency>
    <groupId>com.foo</groupId>
    <artifactId>bar-ejb-client</artifactId>
    <type>ejb-client</type>
    <version>0.0.1</version>
</dependency>
<dependency>
    <groupId>com.foo</groupId>
    <artifactId>bar-test-jar</artifactId>
    <type>test-jar</type>
    <version>0.0.1</version>
</dependency>
```
will result in resolution failure, even if the artifact(s) exist(s) in the repository.

As noted in the **maven-artifact-transfer**'s page: 
> This implies the following:
> * From dependency to artifact is possible, since you can map a type to an extension. However, it is not possible to go from artifact back to dependency, there are several types which have jar as file extension.

When building artifacts for resolution, the above 3 should set artifacts's extension to **jar**.

**Comment by azzazzel** [comment]
Thanks for reporting this issue. I merged your PR and than changed it (see 5a788035adec00828738482befcc008c3b784f59) to make the mapping configurable. 

I also removed the hard-coded values so you will need to add
```xml
<configuration>
	<typeExtensions>
		<ejb>jar</ejb>
		<ejb-client>jar</ejb-client>
		<test-jar>jar</test-jar>
	</typeExtensions>
</configuration>
```
to get the same result
