### ISSUE TITLE
Plugin report ignores arifacts with classifiers

### ISSUE THREAD

**Issue by rgdoliveira** [commsen/bom-helper-maven-plugin#6]
If the BOM has 2 artifacts that does not exist and those 2 artifacts are the same but with different classifiers, one of the artifacts is ignored from the final report.

E.g:
```
      <dependency>
        <groupId>org.kie.kogito</groupId>
        <artifactId>kogito-addons-events-decisions</artifactId>
        <version>999.0.0</version>
      </dependency>
      <dependency>
        <groupId>org.kie.kogito</groupId>
        <artifactId>kogito-addons-events-decisions</artifactId>
        <version>999.0.0</version>
        <classifier>sources</classifier>
      </dependency>
```

Report:
```
[ERROR] Failed to execute goal com.commsen.maven:bom-helper-maven-plugin:0.4.0:resolve (resolve) on project kogito-bom: The following dependencies found in <dependencyManagement> can not be resolved: 
[ERROR]  - Dependency {groupId=org.kie.kogito, artifactId=kogito-addons-events-decisions, version=999.0.0, type=jar}
```

Note that is does not report the artifact with the sources classifier.

I'm proposing that the report would show both artifacts, something like:
```
[ERROR] Failed to execute goal com.commsen.maven:bom-helper-maven-plugin:0.4.0:resolve (resolve) on project kogito-bom: The following dependencies found in <dependencyManagement> can not be resolved: 
[ERROR]  - org.kie.kogito:kogito-addons-events-decisions:jar:sources:999.0.0
[ERROR]  - org.kie.kogito:kogito-addons-events-decisions:jar:999.0.0
```

**Comment by rgdoliveira** [comment]
@azzazzel I proposed solution for this issue in PR https://github.com/commsen/bom-helper-maven-plugin/pull/7

If we want to keep the report in the same way as before, having each part of the artifact separated, like `groupId=foo, artifactID=bar` is also possible, but it would need more changes in the code. Please let me know how you prefer.

**Comment by azzazzel** [comment]
Thank you @rgdoliveira for the report and the contribution! 
I have no strong preference on how it is displayed for as long as the user can tell what is missing. I'll go ahead and merge the PR and make a new release soon.
